id: 51d35b09179e4cf885b6e7b5b18df55d
initial_creation_type: ocr
source_metadata:
  volumes:
    f89be305a6754b06b1a4cf271e1ccac6:
      base_file: v110.txt
      image_group_id: I1PD95956
      title: ''
      total_pages: 1182
      volume_number: 111
